### 20200213
---

**SQLAlchemy 세션 재 연결**

사용자가 데이터베이스 권한이 없거나, OperationalError를 반환했을 때, 강제로 다시 연결하는 방법이다.

연결 풀은 개별 연결과 전체 연결 세트를 새로 고칠 수 있으므로 이전에 풀링 된 연결을 "유효하지 않은"것으로 설정한다.
일반적인 사용 사례는 데이터베이스 서버가 다시 시작될 때 연결 풀이 정상적으로 복구되고 이전에 설정된 모든 연결이 더 이상 작동하지 않는 것이다.

세션에서 연결 해제를 할 때, 연결에 대한 테스트를 수행할 수 있도록 ` create_engine()`을 할 때 `pool_pre_ping=True`를 사용하는 것이다.

라이브에 대한 연결을 테스트하기 위해 사용할 수도 있다.

```python
engine = create_engine("mysql+pymysql://user:pw@host/db", pool_pre_ping=True)
```

일반적으로 풀에서 연결이 체크 아웃 될 때마다 SELECT 1`과 같은 간단한 쿼리를 날린다. 그렇기 떄문에 작은 오버헤드가 있다.

---
#### 참고

https://stackoverflow.com/questions/23747742/sqlalchemy-session-reconnect

https://docs.sqlalchemy.org/en/13/core/pooling.html?highlight=reconnect#dealing-with-disconnects